import { test, expect } from '@playwright/test'

test('3D command center: demo, dynamic repair, WHY, controls and reset', async ({ page, request }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await request.post('/api/simulation/reset')
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Command center' })).toBeVisible()
  await expect(page.locator('canvas')).toBeVisible()
  await expect(page.getByText('Central Medical', { exact: true }).first()).toBeVisible()
  await page.waitForTimeout(1500)
  await page.screenshot({ path: '../artifacts/command-center-ready.png', fullPage: true })
  await page.getByRole('button', { name: 'Run guided demo' }).click()
  await expect(page.getByRole('button', { name: 'Pause' })).toBeVisible()
  await page.getByRole('button', { name: 'Pause' }).click()
  let state = await (await request.get('/api/world-state')).json()
  expect(state.plan.assignments).toHaveLength(4)
  const initialRevision = state.plan.revision
  for (let i = 0; i < 42; i++) await request.post('/api/simulation/step')
  state = await (await request.get('/api/world-state')).json()
  expect(state.demo_step).toBe(5)
  expect(state.plan.revision).toBeGreaterThan(initialRevision)
  expect(state.events.some(e => e.type === 'road_discovered')).toBeTruthy()
  expect(state.decisions.some(d => d.algorithm === 'PlanValidator')).toBeTruthy()
  await expect(page.getByText('Unknown road · online discovery')).toBeVisible()
  const assignmentRow = page.locator('.decision-row').filter({ has: page.locator('.log-stage', { hasText: 'CSP + A*' }) }).first()
  await assignmentRow.getByRole('button', { name: 'WHY' }).click()
  await expect(page.getByRole('dialog', { name: 'Decision explanation' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Enforced constraints' })).toBeVisible()
  await page.screenshot({ path: '../artifacts/decision-explanation.png', fullPage: true })
  await page.getByRole('button', { name: 'Close explanation' }).click()
  await page.screenshot({ path: '../artifacts/command-center-active.png', fullPage: true })
  await page.getByRole('button', { name: 'Inject events', exact: true }).click()
  await page.getByRole('button', { name: 'Compare search algorithms' }).click()
  await expect(page.getByRole('cell', { name: 'A*', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Reopen', exact: true }).click()
  await page.getByRole('button', { name: 'Fail vehicle' }).click()
  await expect.poll(async () => (await (await request.get('/api/world-state')).json()).resources['AMB-01'].available).toBe(false)
  await page.getByRole('button', { name: 'Create emergency' }).click()
  await expect.poll(async () => Object.keys((await (await request.get('/api/world-state')).json()).incidents).length).toBe(3)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: '../artifacts/command-center-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Reset', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Launch demonstration' })).toBeVisible()
  expect(errors).toEqual([])
})
